### ISSUE TITLE
runJaccard error

### ISSUE THREAD

**Issue by plbngl** [r3fang/SnapATAC#10]
Hi Rongxin,

I am running the snATAC workflow following your tutorial (PBMC) and I got this error while running runJaccard.
Could you help with that?

Thank you very much!
Paola
 

x.sp = runJaccard(
	x.sp,
	tmp.folder=tempdir(),
	mat = "bmat",
	max.var=2000,
	ncell.chunk=1000,
	seed.use=10,
	num.cores=5
	)

Epoch: splitting obj into chunks ...
Epoch: scheduling CPUs ...
Epoch: calculating jaccard index for each chunk ...
Error in isOpen(con): invalid connection
Traceback:

**Comment by r3fang** [comment]
Hi Paola,
Can I ask you a few questions?
What OS are you using?
How many cells do you have for x.sp?

This seems to be an error caused by parallel processing. Can you set `num.cores=1` and see what happens?

**Comment by plbngl** [comment]
Hello!

-The OS is CentOS Linux 7 (Core)

- I have 11678 cells:
number of barcodes: 11678
number of bins: 262727
number of genes: 0
number of peaks: 0

- The same error occurs with num.cores=1

Thanks!!!!
Paola

**Comment by r3fang** [comment]
can you reinstall SnapATAC?
if the bug is still not fixed, can you run `runJaccard` with the following cmmand

```R
x.sp = runJaccard(
	x.sp,
	tmp.folder=tempdir(),
	mat = "bmat",
	max.var=2000,
	ncell.chunk=1000,
	seed.use=10,
	do.par=FALSE,
	num.cores=1
	);
```

**Comment by plbngl** [comment]
Thank you!  It works with that command - I will also re-install the program and let you know!

**Comment by plbngl** [comment]
The multi-process option still does not work with the new version...

**Comment by plbngl** [comment]
Hi Rongxin,
I have this other error I can't figure out:

runSnapAddPmat(
	obj=x.sp,
	tmp.folder=tempdir(),
	peak=peak.gr, 
	path.to.snaptools="/home/pbenaglio/.local/bin/snaptools", 
	buffer.size=500
	)
Error in runSnapAddPmatSingle(file, peak = peak, path.to.snaptools = path.to.snaptools, : 'runSnapAddPmat' call failed
Traceback:

1. runSnapAddPmat(obj = x.sp, tmp.folder = tempdir(), peak = peak.gr, 
 .     path.to.snaptools = "/home/pbenaglio/.local/bin/snaptools", 
 .     buffer.size = 500)
2. runSnapAddPmat.default(obj = x.sp, tmp.folder = tempdir(), peak = peak.gr, 
 .     path.to.snaptools = "/home/pbenaglio/.local/bin/snaptools", 
 .     buffer.size = 500)
3. mclapply(fileList, function(file) {
 .     runSnapAddPmatSingle(file, peak = peak, path.to.snaptools = path.to.snaptools, 
 .         buffer.size = buffer.size, tmp.folder = tmp.folder)
 . }, mc.cores = num.cores)
4. lapply(X = X, FUN = FUN, ...)
5. FUN(X[[i]], ...)
6. runSnapAddPmatSingle(file, peak = peak, path.to.snaptools = path.to.snaptools, 
 .     buffer.size = buffer.size, tmp.folder = tmp.folder)
7. stop("'runSnapAddPmat' call failed")

The peak file looks like that:

str(peak.gr)
Formal class 'GRanges' [package "GenomicRanges"] with 7 slots
  ..@ seqnames       :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 24 levels "chr1","chr10",..: 1 2 3 4 5 6 7 8 9 10 ...
  .. .. ..@ lengths        : int [1:24] 9369 4556 4821 5049 2235 3187 3175 3388 4774 1982 ...
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ ranges         :Formal class 'IRanges' [package "IRanges"] with 6 slots
  .. .. ..@ start          : int [1:96911] 237755 521580 566909 569920 713827 752664 762699 780014 801159 805201 ...
  .. .. ..@ width          : int [1:96911] 74 84 97 110 564 165 492 139 91 183 ...
  .. .. ..@ NAMES          : NULL
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ strand         :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 3 levels "+","-","*": 3
  .. .. ..@ lengths        : int 96911
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ seqinfo        :Formal class 'Seqinfo' [package "GenomeInfoDb"] with 4 slots
  .. .. ..@ seqnames   : chr [1:24] "chr1" "chr10" "chr11" "chr12" ...
  .. .. ..@ seqlengths : int [1:24] NA NA NA NA NA NA NA NA NA NA ...
  .. .. ..@ is_circular: logi [1:24] NA NA NA NA NA NA ...
  .. .. ..@ genome     : chr [1:24] NA NA NA NA ...
  ..@ elementMetadata:Formal class 'DataFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 96911
  .. .. ..@ listData       : Named list()
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ elementType    : chr "ANY"
  ..@ metadata       : list()


Thanks!!!

Paola

**Comment by r3fang** [comment]
I believe this is a problem related with the first problem for multi-core processing. I am trying to fix this problem now. This error never happens before. 

Meanwhile, this step basically add cell-by-peak matrix to snap file. can you use the following command:

1) save peak.gr as a bed file in the disc with file name as `peaks.bed`
2) create cell-by-peak matrix using snaptools
```
snaptools snap-add-pmat --snap-file=pbmc.snap --peak-file=peak.bed
```

**Comment by plbngl** [comment]
Hi Thank you very much,
let me understand one thing: the bin/ gene/ peaks matrices can be either added using snaptools (snap-add-bmat / snap-add-gmat/ snap-add-pmat) or using snapATAC (runSnapAddPmat...) - what is the difference or the correct workflow? Thanks!

**Comment by r3fang** [comment]
i updated SnapATAC again to remove the reliance on snaptools for creating cell-by-peak or cell-by-gene matrix. please check in this example https://github.com/r3fang/SnapATAC/blob/master/examples/Fang_2019/Fang_2019.md

now please use `createGmat` and `createPmat` for creating the cell-by-peak/gene matrix.
Let me know if you have any question

Best,
Rongxin

**Comment by plbngl** [comment]
Thank you!
