### ISSUE TITLE
snap@gmat has multiple columns for 1 gene

### ISSUE THREAD

**Issue by hjack123** [r3fang/SnapATAC#100]
x.sp@gmat has multiple columns for each gene,
for plotting it could be misleading. is there a better solution?

**Comment by r3fang** [comment]
Hi, yeah, that’s because the duplicate gene name in the gene file. The easiest way is to make sure there is no duplicates in the gene.gr <http://gene.gr/> object

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego
