### ISSUE TITLE
barcode files

### ISSUE THREAD

**Issue by mej54** [r3fang/SnapATAC#103]
Hi,

I'm wondering where/when the barcode files are created (for example: tac_pbmc_5k_nextgem_singlecell.csv)? I've been looking through the documentation/examples for both snaptools and SnapATAC and I can't seem to figure out how to generate these files.

Thank you!
- Molly

**Comment by r3fang** [comment]
Hi Molly,

The single cell barcode file is created by cell ranger. The reason that I was using barcode file is because many SnapATAC users have run cell ranger for alignement and basic quality control. This is however not required. You can totally start with a fastq or bam file that does not have barcode file. Let me know if you need help with that

**Comment by mej54** [comment]
That makes much more sense now. Thank you very much for your response!

**Comment by qingnanl** [comment]
> Hi Molly, The single cell barcode file is created by cell ranger. The reason that I was using barcode file is because many SnapATAC users have run cell ranger for alignement and basic quality control. This is however not required. You can totally start with a fastq or bam file that does not have barcode file. Let me know if you need help with that
> […](#)
> Sent from my iPhone
> On Sep 25, 2019, at 2:32 PM, Molly Johnson ***@***.***> wrote: Hi, I'm wondering where/when the barcode files are created (for example: tac_pbmc_5k_nextgem_singlecell.csv)? I've been looking through the documentation/examples for both snaptools and SnapATAC and I can't seem to figure out how to generate these files. Thank you! Molly — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

To add on to the question, I was using 10x fastq to generate the .snap file. How can I generate the singlecell.csv in that process? I find the information in the metaData of the .snap file, is that correct?

**Comment by rpique** [comment]
I would like to start without the barcode file, any filtering suggestion?

> Hi Molly, The single cell barcode file is created by cell ranger. The reason that I was using barcode file is because many SnapATAC users have run cell ranger for alignement and basic quality control. This is however not required. You can totally start with a fastq or bam file that does not have barcode file. Let me know if you need help with that

**Comment by r3fang** [comment]
This is redundant with issue [139](https://github.com/r3fang/SnapATAC/issues/139). I will close this issue, please go to issue [139](https://github.com/r3fang/SnapATAC/issues/139)
