### ISSUE TITLE
custom genome

### ISSUE THREAD

**Issue by BingbingYuan** [r3fang/SnapATAC#106]
Can snapATAC deal with custom genome? Based on the description of snaptools snap-pre (below),  I think I can just use any genome build. But, I'm concerning what would be happened when I combine two samples later on. I have two samples, each from different developmental stage. 
 Could you explain a bit more on "This tag does not change anything unless merge or compare multiple snap files"

--genome-name GENOME_NAME
                        genome identifier (i.e. hg19, mm10). This tag does not
                        change anything unless merge or compare multiple snap
                        files. (default: None)
Thanks,

**Comment by r3fang** [comment]
Hi you can totally ignore this tag, it is not used in the downstream analysis
