### ISSUE TITLE
Skip marker annotation step?

### ISSUE THREAD

**Issue by yeswzc** [r3fang/SnapATAC#109]
Hi, 
I want to know if I can skip the step 9 in the **example 10X Adult Mouse Brain**.
I am not sure because I see some steps which may add some objects to x.sp, including:
```
addBmatToSnap(x.sp);
x.sp = createGmatFromMat(...)
# normalize the cell-by-gene matrix
x.sp = scaleCountMatrix( ...)
# smooth the cell-by-gene matrix
x.sp = runMagic(...)
```
Should I perform those if I want to skip annotation?

Thanks!

**Comment by yeswzc** [comment]
Or, is it a bad idea to annotate all the genes in the genome? So, later, I can easily visualize any gene I like.

**Comment by r3fang** [comment]
yes! you can totally skip these steps if you don’t want to annotate the cluster
--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by yeswzc** [comment]
Wow, that's cool.
1. But still a litter bit concerned. Step9 seems did some data normalization. Isn't it saved in the x.sp object and used in the downstream analysis?

2. By the way, is there a document describing the x.sp object?

Thanks!

**Comment by r3fang** [comment]
> But still a litter bit concerned. Step9 seems did some data normalization. Isn't it saved in the x.sp object and used in the downstream analysis?
> 
Step 9. performs count of cell-by-gene table and normalization. It is stored in the x.sp object. If you do not want to annotated the cluster, the cell-by-gene table will not be used for downstream analysis.

> By the way, is there a document describing the x.sp object?
> 
Current not but this is great suggestion!
x.sp contains the following major object
cell-by-bin matrix for clustering analysis
cell-by-peak matrix for feature analysis
cell-by-gene matrix for annotation and integration with scRAN-seq
cell-by-motifi matrix for motif analysis


--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by yeswzc** [comment]
Thanks a lot.
