### ISSUE TITLE
snaptools was supported in windows?

### ISSUE THREAD

**Issue by ChickenWangSY** [r3fang/SnapATAC#11]
I installed snaptools in windows ,but installation was failed.
was failure reason that snaptools didn't support windows?
this is the error information:
< C:\Users\wangshiyou>pip install snaptools
Collecting snaptools
  Using cached https://files.pythonhosted.org/packages/09/31/2e1e6283d860efd3c5fe7ac0e43644a916041e5fba5a5afa97e6a1ec9741/snaptools-1.4.7.tar.gz
Collecting pysam (from snaptools)
  Using cached https://files.pythonhosted.org/packages/15/f6/ce0611aaa1865a616f7dc164fbf046eaf38f2b17c6d404403c56250beb93/pysam-0.15.2.tar.gz
    Complete output from command python setup.py egg_info:
    '.' 不是内部或外部命令，也不是可运行的程序
    或批处理文件。
    '.' 不是内部或外部命令，也不是可运行的程序
    或批处理文件。
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    make: uname: Command not found
    Makefile:228: Extraneous text after `else' directive
    Makefile:231: Extraneous text after `else' directive
    Makefile:231: *** only one `else' per conditional.  Stop.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WANGSH~1\AppData\Local\Temp\pip-install-kf_meyu3\pysam\setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\WANGSH~1\AppData\Local\Temp\pip-install-kf_meyu3\pysam\setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "E:\anaconda\envs\python2\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "E:\anaconda\envs\python2\lib\subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\WANGSH~1\AppData\Local\Temp\pip-install-kf_meyu3\pysam\>

**Comment by r3fang** [comment]
Hello! Unfortunately, snaptools was developed and tested only under UNIX/LINUX system, so far, it has not been made to be compatible with Windows. I will look into this and see if I can it work on Windows today.

**Comment by ChickenWangSY** [comment]
> Hello! Unfortunately, snaptools was developed and tested only under UNIX/LINUX system, so far, it has not been made to be compatible with Windows. I will look into this and see if I can it work on Windows today.

much thanks for your work. the result is anticipated.

**Comment by ChickenWangSY** [comment]
then, a new error appears in snapATAC installation in R
it seems associated with the packages `Rhdf5lib`, the error report is : 
`> install_github("r3fang/SnapATAC")
Downloading GitHub repo r3fang/SnapATAC@master
Installing 4 packages: raster, rhdf5, Rhdf5lib, sp
trying URL 'https://mirrors.tongji.edu.cn/CRAN/src/contrib/raster_2.8-19.tar.gz'
Content type 'application/octet-stream' length 1134627 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/rhdf5_2.26.2.tar.gz'
Content type 'application/x-gzip' length 504692 bytes (492 KB)
==================================================
downloaded 492 KB

trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/Rhdf5lib_1.4.3.tar.gz'
Content type 'application/x-gzip' length 9222338 bytes (8.8 MB)
==================================================
downloaded 8.8 MB

trying URL 'https://mirrors.tongji.edu.cn/CRAN/src/contrib/sp_1.3-1.tar.gz'
Content type 'application/octet-stream' length 1133621 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘Rhdf5lib’ ...
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-c++ accepts -g... yes
checking whether C++ compiler accepts -w... yes
untarring hdf5small_cxx_1.10.3.tar.gz ...
building the szip library...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for config x86_64-unknown-linux-gnu... no
checking for config x86_64-unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-unknown... no
checking for config linux-gnu... found
compiler 'x86_64-conda_cos6-linux-gnu-cc' is GNU gcc-7.3.0
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking whether x86_64-conda_cos6-linux-gnu-cc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of x86_64-conda_cos6-linux-gnu-cc... gcc3
checking how to run the C preprocessor... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp
checking whether make sets $(MAKE)... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-conda_cos6-linux-gnu-cc... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld
checking if the linker (/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-nm
checking the name lister (/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld option to reload object files... -r
checking for objdump... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-strip
checking for ranlib... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib
checking command to parse /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-nm output from x86_64-conda_cos6-linux-gnu-cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-conda_cos6-linux-gnu-cc supports -fno-rtti -fno-exceptions... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to produce PIC... -fPIC -DPIC
checking if x86_64-conda_cos6-linux-gnu-cc PIC flag -fPIC -DPIC works... yes
checking if x86_64-conda_cos6-linux-gnu-cc static flag -static works... yes
checking if x86_64-conda_cos6-linux-gnu-cc supports -c -o file.o... yes
checking if x86_64-conda_cos6-linux-gnu-cc supports -c -o file.o... (cached) yes
checking whether the x86_64-conda_cos6-linux-gnu-cc linker (/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for build mode... production
checking for math library support... no
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for error_at_line... yes
checking for working memcmp... yes
checking for vprintf... yes
checking for _doprnt... no
checking for memset... yes
checking if encoding enabled... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/SZconfig.h
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in src
make[1]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make  all-am
make[2]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I.   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT rice.lo -MD -MP -MF .deps/rice.Tpo -c -o rice.lo rice.c
libtool: compile:  x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT rice.lo -MD -MP -MF .deps/rice.Tpo -c rice.c  -fPIC -DPIC -o rice.o
mv -f .deps/rice.Tpo .deps/rice.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I.   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT sz_api.lo -MD -MP -MF .deps/sz_api.Tpo -c -o sz_api.lo sz_api.c
libtool: compile:  x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT sz_api.lo -MD -MP -MF .deps/sz_api.Tpo -c sz_api.c  -fPIC -DPIC -o sz_api.o
mv -f .deps/sz_api.Tpo .deps/sz_api.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I.   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT encoding.lo -MD -MP -MF .deps/encoding.Tpo -c -o encoding.lo encoding.c
libtool: compile:  x86_64-conda_cos6-linux-gnu-cc -DHAVE_CONFIG_H -I. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -MT encoding.lo -MD -MP -MF .deps/encoding.Tpo -c encoding.c  -fPIC -DPIC -o encoding.o
mv -f .deps/encoding.Tpo .deps/encoding.Plo
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-conda_cos6-linux-gnu-cc  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -w -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions -version-info 2:0:0 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -o libsz.la -rpath /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib rice.lo sz_api.lo encoding.lo  -lm
libtool: link: /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ar cru .libs/libsz.a  rice.o sz_api.o encoding.o
libtool: link: /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib .libs/libsz.a
libtool: link: ( cd ".libs" && rm -f "libsz.la" && ln -s "../libsz.la" "libsz.la" )
make[2]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make[1]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make[1]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
Making install in src
make[1]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make[2]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
 /bin/mkdir -p '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libsz.la '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib'
libtool: install: /usr/bin/install -c .libs/libsz.lai /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib/libsz.la
libtool: install: /usr/bin/install -c .libs/libsz.a /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib/libsz.a
libtool: install: chmod 644 /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib/libsz.a
libtool: install: /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib/libsz.a
libtool: finish: PATH="/hwfssz1/ST_MCHRI/CLINIC/SOFTWARES/bin:.:/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/bin:/lfs1/ST_PMO2015G/STN11023/bin:/share/backup/wuliang2/software/lib/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/cmake-3.8.2-Linux-x86_64/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/hisat2-2.1.0:/lfs1/ST_PMO2015G/STN11023/bin/bin:/usr/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages/Anaconda2/bin:/hwfssz1/ST_MCHRI/CLINIC/SOFTWARES/bin:.:/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/bin:/lfs1/ST_PMO2015G/STN11023/bin:/share/backup/wuliang2/software/lib/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/cmake-3.8.2-Linux-x86_64/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/hisat2-2.1.0:/lfs1/ST_PMO2015G/STN11023/bin/bin:/usr/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages/Anaconda2/bin:.:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/bin:/lfs1/ST_PMO2015G/STN11023/bin:/share/backup/wuliang2/software/lib:/lfs1/ST_PMO2015G/STN11023/bin/bin:/usr/bin:/hwfssz1/ST_MCHRI/CLINIC/SOFTWARES/bin:/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/cellranger-3.0.2:/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin:/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/condabin:/hwfssz1/ST_MCHRI/CLINIC/SOFTWARES/bin:.:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/bin:/lfs1/ST_PMO2015G/STN11023/bin:/share/backup/wuliang2/software/lib/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/cmake-3.8.2-Linux-x86_64/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wuliang2/biosoftware/hisat2-2.1.0:/lfs1/ST_PMO2015G/STN11023/bin/bin:/usr/bin/#:/hwfssz1/ST_MCHRI/STEMCELL/USER/wangshiyou/packages/Anaconda2/bin:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bio/ncbi/bin:/opt/bio/mpiblast/bin:/opt/bio/EMBOSS/bin:/opt/bio/clustalw/bin:/opt/bio/tcoffee/bin:/opt/bio/hmmer/bin:/opt/bio/phylip/exe:/opt/bio/mrbayes:/opt/bio/fasta:/opt/bio/glimmer/bin:/opt/bio/glimmer/scripts:/opt/bio/gromacs/bin:/opt/bio/gmap/bin:/opt/bio/tigr/bin:/opt/bio/autodocksuite/bin:/opt/bio/wgs/bin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/condor/bin:/opt/condor/sbin:/opt/gridengine/bin/lx-amd64:/lfs1/ST_PMO2015G/STN11023/software/weblogo:/lfs1/ST_PMO2015G/STN11023/software/Homer/bin:/home/wangshiyou/bin:/sbin" ldconfig -n /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/include'
 /usr/bin/install -c -m 644 ricehdf.h szip_adpt.h szlib.h '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/szip/include'
make[2]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make[1]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip/src'
make[1]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
make[2]: Entering directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
make[1]: Leaving directory '/tmp/Rtmp4EKYlS/R.INSTALL5e47640b17a7/Rhdf5lib/src/hdf5/szip'
checking how to run the C preprocessor... /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp
cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directory
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking if zlib is wanted... yes
checking for inflateEnd in -lz... no
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking zlib in /usr... failed
configure: error: either specify a valid zlib installation with --with-zlib=DIR or disable zlib usage with --without-zlib
ERROR: configuration failed for package ‘Rhdf5lib’
* removing ‘/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/R/library/Rhdf5lib’
Error in i.p(...) :
  (converted from warning) installation of package ‘Rhdf5lib’ had non-zero exit status`

I seek this error and found it due to that anaconda can't find  zlib.a library. But I still can't finish this error .  what's your advice ?

regards!

**Comment by r3fang** [comment]
this is likely because zlib is not installed on your machine:

```bash
conda install -c anaconda zlib
conda install -c bioconda bioconductor-rhdf5
```

**Comment by r3fang** [comment]
Does it solve the problem?

**Comment by ChickenWangSY** [comment]
> Does it solve the problem?

`zlib` and `rhd5` were installed successfully and I 'm trying to install snapATAC again.  then , the network is bad and installation is slow.

**Comment by ChickenWangSY** [comment]
> > Does it solve the problem?
> 
> `zlib` and `rhd5` were installed successfully and I 'm trying to install snapATAC again. then , the network is bad and installation is slow.

yeah,  you're right.  installation is done. : )
much thanks for your help again.

**Comment by r3fang** [comment]
Thanks! Please feel free to let me know if you have other questions. I will close this issue for now
