### ISSUE TITLE
Combine 10X scATAC FASTQs before dex-fastq ?

### ISSUE THREAD

**Issue by hamishking** [r3fang/SnapATAC#12]
Hi there,
I just wanted to know if there is any problem in combining FASTQ files from multiple sequencing lanes from the same 10X scATAC library before the dex-fastq command, rather than after as shown in the tutorial. I have data from two NextSeq runs so each library has eight lanes total, and I have four samples. Seems much more convenient to therefore combine FASTQs together before the dex-fastq but I just wanted to check that this wouldn't create any problems later in the analysis pipeline. FASTQ files are made with standard cellranger-atac mkfastq.  This is what I had in mind.

cat FASTQ/GC-HK-8248/outs/fastq_path/H3J5TBGXB/BCP003/\*R1* \\
    FASTQ/GC-HK-8293/outs/fastq_path/H7JLKBGXB/BCP003/\*R1* > BCP003_scATAC_R1_fastq.gz  
cat FASTQ/GC-HK-8248/outs/fastq_path/H3J5TBGXB/BCP003/\*I1* \\
    FASTQ/GC-HK-8293/outs/fastq_path/H7JLKBGXB/BCP003/\*I1* > BCP003_scATAC_I1_fastq.gz  
cat FASTQ/GC-HK-8248/outs/fastq_path/H3J5TBGXB/BCP003/\*R3* \\
    FASTQ/GC-HK-8293/outs/fastq_path/H7JLKBGXB/BCP003/\*R3* > BCP003_scATAC_R3_fastq.gz  

snaptools dex-fastq --input=BCP003_scATAC_R1_fastq.gz \\
                    --output=BCP003_scATAC_R1_fastq.dex.gz \\
                    --index-fastq-list=BCP003_scATAC_I1_fastq.gz

snaptools dex-fastq --input=BCP003_scATAC_R3_fastq.gz \\
                    --output=BCP003_scATAC_R3_fastq.dex.gz \\
                    --index-fastq-list=BCP003_scATAC_I1_fastq.gz

Thanks in advance

Hamish

**Comment by r3fang** [comment]
Hi Hamish,

This is totally fine! The only reason I demultiplex each file separately is because this can run demultiplexing in parallel which could be faster. but in terms of the result, these two should result in the same file.

Best,
Rongxin

**Comment by hamishking** [comment]
Hi Rongxin,
Thanks for the quick reply! 
Am I right in saying that the demultiplexing is not able to run on multiple cores then? If so, it seems like running the individual FASTQ files would be faster.
Hamish

**Comment by r3fang** [comment]
Hi Hamish,

You are totally right about it. 

-R
