### ISSUE TITLE
runMACS ERROR

### ISSUE THREAD

**Issue by mchill2** [r3fang/SnapATAC#127]
Hello,

Got through to runMACS and then came up with the following error:

> runMACS(
+   obj=EC1x.sp[which(EC1x.sp@cluster==1),], 
+   output.prefix="Endo_1.1",
+   path.to.snaptools="/home/martinlab/.conda/envs/snapATAC/lib/python2.7/site-packages/snaptools/",
+   path.to.macs="/usr/bin/macs2",
+   gsize="mm", 
+   buffer.size=500, 
+   num.cores=10,
+   macs.options="--nomodel --shift 37 --ext 73 --qval 1e-2 -B --SPMR --call-summits",
+   tmp.folder=tempdir()
+ )
Epoch: checking input parameters ... 
Epoch: extracting fragments from each snap files ...
sh: 1: /home/martinlab/.conda/envs/snapATAC/lib/python2.7/site-packages/snaptools/: Permission denied
cat: /tmp/RtmprHDfTz/file50929778f62.bed.gz: No such file or directory
INFO  @ Tue, 26 Nov 2019 23:38:19: 
# Command line: callpeak -t /tmp/RtmprHDfTz/file50921961618d.bed.gz -f BED -g mm --nomodel --shift 37 --ext 73 --qval 1e-2 -B --SPMR --call-summits -n Endo_1.1
# ARGUMENTS LIST:
# name = Endo_1.1
# format = BED
# ChIP-seq file = ['/tmp/RtmprHDfTz/file50921961618d.bed.gz']
# control file = None
# effective genome size = 1.87e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Searching for subpeak summits is on
# MACS will save fragment pileup signal per million reads
 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 read tag files... 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 read treatment tags... 
Exception ZeroDivisionError: 'integer division or modulo by zero' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 tag size is determined as 0 bps 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 tag size = 0 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1  total tags in treatment: 0 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 user defined the maximum tags... 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Tue, 26 Nov 2019 23:38:19: #1  tags after filtering in treatment: 0 
Traceback (most recent call last):
  File "/usr/bin/macs2", line 614, in <module>
    main()
  File "/usr/bin/macs2", line 56, in main
    run( args )
  File "/usr/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 109, in run
    info("#1  Redundant rate of treatment: %.2f", float(t0 - t1) / t0)
ZeroDivisionError: float division by zero
Error in runMACS(obj = EC1x.sp[which(EC1x.sp@cluster == 1), ], output.prefix = "Endo_1.1",  : 
  'MACS' call failed

Any help would be most appreciated. 

Best

**Comment by mfisher1995** [comment]
Was this ever resolved? I am running into the same error.
