### ISSUE TITLE
Convert BAM files (Cell ranger) to SNAP files

### ISSUE THREAD

**Issue by AitorAndueza** [r3fang/SnapATAC#134]
Hello,

I am new with bioinformatics and I am trying to convert Ban files generated with cell ranger into Snap file following these instructions: https://github.com/r3fang/SnapATAC/wiki/FAQs#cellranger_output

However, I have an issue in this step:
$ samtools sort -n -@ 10 -m 1G atac_v1_adult_brain_fresh_5k_possorted.snap.bam -o atac_v1_adult_brain_fresh_5k.snap.nsrt.bam

In stead of generating just one snap.nsrt.bam file, it generates me 350 files, named from 1 to 350. Therefore, I don't know how to continue in the next step.

Can someone help me? I would really appreciate your help.

Best,

Aitor

**Comment by yeswzc** [comment]
It means the 'samtools sort' step had not finished. Wait till samtools finish the job, if failed try again.

**Comment by AitorAndueza** [comment]
Ok, I will tried again. Anyway, when the samtools sort function is running and generating this files, an error appear. It says that more symbols or letters are needed. Is it correct or it is weird?

**Comment by yeswzc** [comment]
I've never seen see before. Do you mind to give a screen shot of the reported error?

**Comment by AitorAndueza** [comment]
Thank you for your help. The error was solved updating the new Snaptools version. Thank you though.

**Comment by r3fang** [comment]
@yeswzc thanks for solving the issue!
