### ISSUE TITLE
Error in H5Dread

### ISSUE THREAD

**Issue by huidongchen** [r3fang/SnapATAC#14]
Hi Rongxin,

Thanks for creating such a fantastic tool! 

Unfortunately I'm running into some expected errors when analyzing a scATAC-seq dataset (starting with .bam files). I have completed Step 6 so far (following https://github.com/r3fang/SnapATAC/blob/master/examples/10X_P50/README.md) and got both .snap file and .snap.qc file. 

But when I ran `createSnap`, the error happened. 
```
Epoch: reading the barcode session ...
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
Error in data.frame(barcode, TN, UM, PP, UQ, CM): arguments imply differing number of rows: 0, 2034
Traceback:

1. createSnap(file = "Buenrostro2018.snap", sample = "Buenrostro2018", 
 .     do.par = TRUE, num.cores = 5)
2. createSnap.default(file = "Buenrostro2018.snap", sample = "Buenrostro2018", 
 .     do.par = TRUE, num.cores = 5)
3. mclapply(as.list(seq(fileList)), function(i) {
 .     createSnapSingle(file = fileList[[i]], sample = sampleList[[i]])
 . }, mc.cores = num.cores)
4. lapply(X = X, FUN = FUN, ...)
5. FUN(X[[i]], ...)
6. createSnapSingle(file = fileList[[i]], sample = sampleList[[i]])
7. readMetaData(file)
8. readMetaData.default(file)
9. data.frame(barcode, TN, UM, PP, UQ, CM)
10. stop(gettextf("arguments imply differing number of rows: %s", 
  .     paste(unique(nrows), collapse = ", ")), domain = NA)
```

I tried to research online but without success. I would truly appreciate it if you could help me out here.

I'm listing some info of .qc file and also output from Step 6 in case it might be helpful for you.
from .qc
```
Total number of unique barcodes:             2034
TN - Total number of fragments:              495280829
UM - Total number of uniquely mapped:        180290059
SE - Total number of single ends:            0
SA - Total number of secondary alignments:   0
PE - Total number of paired ends:            180290059
PP - Total number of proper paired:          180131064
PL - Total number of proper frag len:        180115491
US - Total number of usable fragments:       180115491
UQ - Total number of unique fragments:       42089297
CM - Total number of chrM fragments:         17396249
```
from Step6
```
===== reading the barcodes and bins ======
@AM     nBinSize:1
@AM     binSizeList: [5000]
@AM     binSize:5000    nBin:627478
```

Many thanks!

Best,
Huidong

**Comment by r3fang** [comment]
Hi Huidong,

This is likely because the dependencies Rhdf5 and  Rhdf5lib are not successfully installed. Can you install these two R packages separately? Also what's the R version that you are using?

https://bioconductor.org/packages/3.7/bioc/html/rhdf5.html

Let me know if this still does not solve the problem 

-R

**Comment by huidongchen** [comment]
Thanks so much for your prompt reply. Installing both **Rhdf5** and **Rhdf5lib** solved the issue!

**Comment by r3fang** [comment]
Wonderful!

**Comment by xiatianjihao** [comment]
Hi Rongxin, 
I have installed the rhdf5(verion=2.28.0) and Rhdf5lib(version=1.6.1) for R3.6.1, but the same issue still appeared. Are there some other problems?
Thank you!

**Comment by r3fang** [comment]
Hi,

I found that Rhdf5 package does not work well on R 3.6 (development version). Do you have access to R 3.5 or 3.4?
--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by xiatianjihao** [comment]
Thank you very much! It worked well when I used R 3.5.
