### ISSUE TITLE
snaptools dex-fastq input argument 10x barcodes

### ISSUE THREAD

**Issue by smanne07** [r3fang/SnapATAC#15]
Hi,
I had a question about the `--index-fastq-list` argument to dex-fastq command,is this input a file with cell indices like 10x barcode file for 10x fastq files?

I wanted to make sure it is actually R2 file instead of I1 file ,the tutorial here says I1(https://github.com/r3fang/SnapATAC/wiki/FAQs#CEMBA_snap).

Best regards
Sasi

**Comment by r3fang** [comment]
Hi Sasi,

The tutorial you have pointed to is not 10X single cell ATAC-seq. The barcode design is quite different from 10X dataset. Please refer to this example for demultiplexing for 10X dataset

https://github.com/r3fang/SnapATAC/blob/master/examples/10X_P50/README.md

Best,
-R

**Comment by smanne07** [comment]
Thank you for clarifying!

The tutorial i pointed has 10x subsection(How to create snap file from 10X dataset?),so was confused.

**Comment by r3fang** [comment]
Sorry. should have made it more clear
