### ISSUE TITLE
promoter file not found

### ISSUE THREAD

**Issue by Zepeng-Mu** [r3fang/SnapATAC#16]
Hi, I ran `system("wget http://renlab.sdsc.edu/r3fang/share/Fang_2019/published_scATAC/PBMC_10k_10X/atac_v1_pbmc_10k_fastqs/promoter.bed")` in Rstudio but got:

```
--2019-05-01 11:25:27--  http://renlab.sdsc.edu/r3fang/share/Fang_2019/published_scATAC/PBMC_10k_10X/atac_v1_pbmc_10k_fastqs/promoter.bed
Resolving renlab.sdsc.edu (renlab.sdsc.edu)... 198.202.90.216
Connecting to renlab.sdsc.edu (renlab.sdsc.edu)|198.202.90.216|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-01 11:25:27 ERROR 404: Not Found.
```

Thanks

**Comment by r3fang** [comment]
Hi,

Please use this link
http://renlab.sdsc.edu/r3fang/share/Fang_2019/published_scATAC/atac_v1_pbmc_10k_fastqs/promoter.bed

Sorry for the inconvenience! 

Best,
-RF
