### ISSUE TITLE
Sample integration - advice

### ISSUE THREAD

**Issue by hamishking** [r3fang/SnapATAC#17]
Hi there,

I have four 10X scATACseq libraries (from four independent tissue donors) and have run them through SnapATAC pipeline (same as in the 10X PBMC tutorial).

However there is a clear batch/sample-specific effect when I look at the UMAP visualisation (see below). I have tried both normOVE and normOVN at the runNormJaccard step. I have also performed scRNA-seq on the exact same samples, and when I normalise/integrate those matching datasets I have not seen any major sample-specific effects.

Do you have any advice on improving or troubleshooting this?

Thanks,

Hamish

![snapatac](https://user-images.githubusercontent.com/42668604/57152426-6a41da00-6dcb-11e9-9f62-ace0f870075e.png)

**Comment by r3fang** [comment]
Hi Hamish,

At least from the plot, it seems to me that there are not very strong batch effect. For instance, you do see a mixture of clusters for yellow and green and red samples. 

When you analyze single cell RNA-seq, did you use any batch effector corrector?

Best,
-R

**Comment by hamishking** [comment]
Thanks for the quick reply!

Yes, some of the clusters are equally mixed between samples. However other clusters are made only of a single sample (see downsampled plot below), like clusters 12 and 14. In fact I guess one sample is the most problematic - BCP6. For the scRNA-seq I have used both Seurat V3 Integrate and Scanpy and not observed this strong an effect for this sample.

![snapatac_1000](https://user-images.githubusercontent.com/42668604/57152978-ff919e00-6dcc-11e9-8f70-63f373c6aec1.png)
![clusters](https://user-images.githubusercontent.com/42668604/57152979-01f3f800-6dcd-11e9-8139-37d9f8790fe0.png)

I've also compared the different sequencing/alignment stats for the samples - no major differences.

![snapatac QC](https://user-images.githubusercontent.com/42668604/57153137-6dd66080-6dcd-11e9-94cb-e16ed9491e9f.png)

Any ideas?

**Comment by r3fang** [comment]
This is a bit surprise to me. because we found usually the chromatin accessibility is more stable and batch effect is much less frequently observed as compared to scRNA-seq. I wonder when you run Saurat V3, did you perform batch effect correction? If yes, then that might explain why. The normalization of Jaccard index is only to remove the bias introduced by red depth or other artificial factor but does not remove the batch effect. These two are different components. I agree with you BCP6 seems to be quite different from other samples. 

Meanwhile, I am testing some batch effect corrector algorithms, planning to integrate this component in the near future. 

 Best,
-R

**Comment by r3fang** [comment]
btw, your distribution plot looks great ;)

**Comment by r3fang** [comment]
Dear Hamish,

I added Harmony to the pipeline for data integration and batch effect correction. You might need to update SnapATAC tho. 
See https://github.com/r3fang/SnapATAC/tree/master/examples/10X_sci

It works pretty well on the demo example:
![image](https://user-images.githubusercontent.com/6808347/57185286-40e18680-6e7d-11e9-963f-1bf8cccf8abd.png)

Hopefully this is helpful!

Best,
-R

**Comment by hamishking** [comment]
Hi Rongxin,

This is fantastic, thank you for your speed incorporating Harmony into the pipeline. My samples now look much better aligned/integrated!

Thank you!

Hamish

![image](https://user-images.githubusercontent.com/42668604/57289320-0cefa680-70b3-11e9-9783-59ccd17af97f.png)

**Comment by r3fang** [comment]
That's great!

**Comment by r3fang** [comment]
i'll close this issue, but please let me know if you have other questions
