### ISSUE TITLE
convert seurat object to snap object

### ISSUE THREAD

**Issue by rojinsafavi** [r3fang/SnapATAC#171]
Is there a way to convert Seurat object to snap object?

**Comment by shaniAmare** [comment]
I'm also interested to know whether anyone has attempted it, or planning to do as. Similarly to convert it to an SCE object as well.

**Comment by Ajaingithub** [comment]
> Is there a way to convert Seurat object to snap object?

Hi @rojinsafavi 

How did you convert the seurat object to snap?
