### ISSUE TITLE
Filtering samples in snap object?

### ISSUE THREAD

**Issue by Zepeng-Mu** [r3fang/SnapATAC#18]
Hi,
Maybe I missed it in the tutorial but is there a function to filter barcodes based on some criteria in the snap object without extracting separate data matrix?
Thanks

**Comment by r3fang** [comment]
Hi Zepeng,

Yes, the function is:

```R
> x.sp = filterCells(
	obj=x.sp, 
	subset.names=c("fragment.num", "UMI"),
	low.thresholds=c(1000,1000),
	high.thresholds=c(Inf, Inf)
	);
```

`createSnap` creates a snap object and load the quality control metrics. `filterCells` remove cells of low quality before loading the sparse matrix.

Does it answer your question?

-R

**Comment by Zepeng-Mu** [comment]
Can I input a list of barcodes and filter them out?

**Comment by r3fang** [comment]
Yes.

```R
> barcode.sel = c("barcode1", "barcode2");
> x.sp = x.sp[which(x.sp@barcode %in% barcode.sel),];
```

**Comment by Zepeng-Mu** [comment]
Oh, this actually can filter all the components in the data object?
Thank you so much!
