### ISSUE TITLE
problem running snaptools

### ISSUE THREAD

**Issue by ninal88** [r3fang/SnapATAC#180]
Hi,
I've been trying to instal snaptools both with the git clone and I get the following error:

Traceback (most recent call last):
  File "./bin/snaptools", line 36, in <module>
    from snaptools.parser import parse_args
ImportError: No module named snaptools.parser

Any help will be appreciated!

**Comment by jindalk** [comment]
Hi, I've encountered this same error in the past. Turns out I did not have python3 loaded in my environment (I was running this on a cluster).

**Comment by ninal88** [comment]
Yep, I figured it out eventually. Just forgot to close the issue. 

Thanks for the confirmation.
