### ISSUE TITLE
pybedtools error when install python snaptools

### ISSUE THREAD

**Issue by FangmingXie** [r3fang/SnapATAC#2]
When I try to install the python snaptools package, I receive this error message (attached) about failed to install pybedtools due to some c++ errors. Just wondering if you have any ideas on how this could be fixed?
![snipaste_2019-02-26_12-26-11](https://user-images.githubusercontent.com/27909240/53449018-b76d8e00-39cd-11e9-9ec6-88ef36fb809f.png)

**Comment by r3fang** [comment]
Maybe pre-install `pysam` and `pybedtools` use conda first:

```bash
$ conda install -c bioconda pysam 
$ conda install -c bioconda pybedtools 
$ pip install snaptools==1.2.5
```

**Comment by r3fang** [comment]
this usually solves the problem

**Comment by FangmingXie** [comment]
Thanks, that works.
