### ISSUE TITLE
intstall snaptools in linux by python 3.7 in anaconda

### ISSUE THREAD

**Issue by ChickenWangSY** [r3fang/SnapATAC#21]
Hi, 
     when I use `pip3.7` and `python 3.7` installed by anaconda, I got an error : 

`$pip3 install snaptools
Collecting snaptools
Requirement already satisfied: pysam in ./anaconda3/lib/python3.7/site-packages (from snaptools) (0.15.2)
Collecting pybedtools>=0.7 (from snaptools)
  Using cached https://files.pythonhosted.org/packages/ca/b6/af143d5247cfe331e32c96ca92056293140eb8ce788d37842f6dcea734b4/pybedtools-0.8.0.tar.gz
Requirement already satisfied: h5py in ./anaconda3/lib/python3.7/site-packages (from snaptools) (2.8.0)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from snaptools) (0.17.1)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from snaptools) (1.15.4)
Collecting python-louvain (from snaptools)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from pybedtools>=0.7->snaptools) (1.12.0)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from python-louvain->snaptools) (2.2)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/lib/python3.7/site-packages (from networkx->python-louvain->snaptools) (4.3.0)
Building wheels for collected packages: pybedtools
  Building wheel for pybedtools (setup.py) ... error
  ERROR: Complete output from command /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9zkhoi0h/pybedtools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0raptwhn --python-tag cp37:
  ERROR: running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/helpers.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/parallel.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/genome_registry.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/stats.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/bedtool.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/version.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/logger.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/paths.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/__main__.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/filenames.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/__init__.py -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/settings.py -> build/lib.linux-x86_64-3.7/pybedtools
  creating build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_iter.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_len_leak.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_helpers.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_cbedtools.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_issues.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/tfuncs.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_gzip_support.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/regression_tests.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/__init__.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test1.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_scripts.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  copying pybedtools/test/test_contrib.py -> build/lib.linux-x86_64-3.7/pybedtools/test
  creating build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/intersection_matrix.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/bigbed.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/bigwig.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/venn_maker.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/__init__.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/long_range_interaction.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  copying pybedtools/contrib/plotting.py -> build/lib.linux-x86_64-3.7/pybedtools/contrib
  creating build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/intersection_matrix.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/venn_mpl.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/intron_exon_reads.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/venn_gchart.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/__init__.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/peak_pie.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/py_ms_example.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  copying pybedtools/scripts/annotate.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  creating build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/__init__.py -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  running egg_info
  creating pybedtools.egg-info
  writing pybedtools.egg-info/PKG-INFO
  writing dependency_links to pybedtools.egg-info/dependency_links.txt
  writing requirements to pybedtools.egg-info/requires.txt
  writing top-level names to pybedtools.egg-info/top_level.txt
  writing manifest file 'pybedtools.egg-info/SOURCES.txt'
  reading manifest file 'pybedtools.egg-info/SOURCES.txt'
  writing manifest file 'pybedtools.egg-info/SOURCES.txt'
  copying pybedtools/cbedtools.cpp -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/featurefuncs.cpp -> build/lib.linux-x86_64-3.7/pybedtools
  creating build/lib.linux-x86_64-3.7/pybedtools/include
  copying pybedtools/include/bedFile.cpp -> build/lib.linux-x86_64-3.7/pybedtools/include
  copying pybedtools/include/fileType.cpp -> build/lib.linux-x86_64-3.7/pybedtools/include
  copying pybedtools/include/gzstream.cpp -> build/lib.linux-x86_64-3.7/pybedtools/include
  copying pybedtools/test/data/gdc.50.200.bam.bai -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/a.links.html -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.othersort.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/exons.gff -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/BEAF_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/SuHw_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/venn.c.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/x.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/test.fa.fai -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.gff.gz -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/test_tsses.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/test.fa -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/BEAF_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/Cp190_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/d.gff -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/bedpe2.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/y.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/small.fastq -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/1000genomes-example.vcf -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/snps.bed.gz -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.gff -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/164.gtf -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/expand_test.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/rmsk.hg18.chr21.small.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.sorted.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/a.igv_script -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.sorted.bam.bai -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/hg38-base.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/hg19.gff -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/tag_test1.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/democonfig.yaml -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/a.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/v.vcf -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/hg38-problem.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.1.100.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/issue_121.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/bedpe.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/CTCF_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/SuHw_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/test_bedpe.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/m1.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/Cp190_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/vcf-stderr-test.vcf -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/multibamcov_test.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/CTCF_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/mm9.bed12 -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/vcf-stderr-test.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/dm3-chr2L-5M.gff.gz -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/tag_test2.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/c.gff -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/test_peaks.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/rmsk.hg18.chr21.small.bed.gz -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/x.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/dm3-chr2L-5M-invalid.gff.gz -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.50.200.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/venn.b.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/reads.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/small.bam -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/b.bed -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/test/data/gdc.1.100.bam.bai -> build/lib.linux-x86_64-3.7/pybedtools/test/data
  copying pybedtools/cbedtools.pyx -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/featurefuncs.pyx -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/_Window.pyx -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/cbedtools.pxd -> build/lib.linux-x86_64-3.7/pybedtools
  copying pybedtools/scripts/pybedtools -> build/lib.linux-x86_64-3.7/pybedtools/scripts
  creating build/lib.linux-x86_64-3.7/pybedtools/scripts/examples
  copying pybedtools/scripts/examples/pbt_plotting_example.py -> build/lib.linux-x86_64-3.7/pybedtools/scripts/examples
  running build_ext
  building 'pybedtools.cbedtools' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/pybedtools
  creating build/temp.linux-x86_64-3.7/pybedtools/include
  /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Ipybedtools/include/ -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include/python3.7m -c pybedtools/cbedtools.cpp -o build/temp.linux-x86_64-3.7/pybedtools/cbedtools.o
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  In file included from pybedtools/include/bedFile.h:16:0,
                   from pybedtools/cbedtools.cpp:660:
  pybedtools/include/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
   #include <zlib.h>`
   `         ^~~~~~~~
  compilation terminated.
  error: command '/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1`
  ----------------------------------------
  `ERROR: Failed building wheel for pybedtools
  Running setup.py clean for pybedtools
  ERROR: Complete output from command /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9zkhoi0h/pybedtools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: option --all not recognized`
  ----------------------------------------
  `ERROR: Failed cleaning build dir for pybedtools
Failed to build pybedtools
Installing collected packages: pybedtools, python-louvain, snaptools
  Running setup.py install for pybedtools ... error
    ERROR: Complete output from command /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9zkhoi0h/pybedtools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pfq4ta4c/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    copying pybedtools/version.py -> build/lib.linux-x86_64-3.7/pybedtools
    running egg_info
    writing pybedtools.egg-info/PKG-INFO
    writing dependency_links to pybedtools.egg-info/dependency_links.txt
    writing requirements to pybedtools.egg-info/requires.txt
    writing top-level names to pybedtools.egg-info/top_level.txt
    reading manifest file 'pybedtools.egg-info/SOURCES.txt'
    writing manifest file 'pybedtools.egg-info/SOURCES.txt'
    running build_ext
    building 'pybedtools.cbedtools' extension
    /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Ipybedtools/include/ -I/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/include/python3.7m -c pybedtools/cbedtools.cpp -o build/temp.linux-x86_64-3.7/pybedtools/cbedtools.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from pybedtools/include/bedFile.h:16:0,
                     from pybedtools/cbedtools.cpp:660:
    pybedtools/include/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
     #include <zlib.h>
              ^~~~~~~~
    compilation terminated.
    error: command '/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1`
    ----------------------------------------
`ERROR: Command "/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9zkhoi0h/pybedtools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pfq4ta4c/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-9zkhoi0h/pybedtools/`
Do you know the reason of that ?   how can I solve it ? 

regards!

**Comment by r3fang** [comment]
Hi, this is likely because it fails to install pybedtools, which is the most common error. Can you pre-install pybedtools separately and see if it solves the problem.

**Comment by ChickenWangSY** [comment]
> Hi, this is likely because it fails to install pybedtools, which is the most common error. Can you pre-install pybedtools separately and see if it solves the problem.

oh, it works.  much thanks for your help !!!  :)
