### ISSUE TITLE
peak_bc_matrix_mex_matrix.mtx file from 10X?

### ISSUE THREAD

**Issue by EDYAC** [r3fang/SnapATAC#23]
Hello,
I recently did a single cell ATAC-seq experiment, the facility gave me back a bam file, bed file and a matrix called peak_bc_matrix...mtx, can I start the analysis using the matrix? if so, how?
Thank you!
E.

**Comment by r3fang** [comment]
Hello,

Yes. You can start with either .bam or bed file from cell-ranger pipeline. Here is detailed instruction:
https://github.com/r3fang/SnapATAC/wiki/FAQs#cellranger_output

Unfortunately, SnapATAC does not support cell-by-peak matrix. One thing we have learned is that a significantly portion of reads in single cell ATAC-seq library are outside the peaks identified from aggregate signal, these reads are also very useful for clustering. Cell-by-peak matrix does not include these reads. Also, using cell-by-peaks matrix will make it difficult for integrative analysis when adding another sample.

Please let me know if you need other help!
-R

**Comment by EDYAC** [comment]
Hey R, 
Thank you for your response, 
I have a bam.bam file and a bam.bam.bai file, which one to use?
And is there a big difference if I use the BAM file instead of the Bed file?
Thank you,
E

**Comment by r3fang** [comment]
1) you should use `bam.bam` file instead of `bai` file. 
2) These two (bam and bed), in theory, should yield in similar result, but haven't compared them yet. My impression is bam file was unfiltered? which I always use as an entry point for my analysis

**Comment by EDYAC** [comment]
Ok thank you for your response. Appreciate it.
I will let you know if I have more questions.
