### ISSUE TITLE
$ snaptools snap-pre

### ISSUE THREAD

**Issue by EDYAC** [r3fang/SnapATAC#24]
Hello,
I'm trying to execute that in my terminal, i've changed the directory and input the file name.
I'm using human genome, so in --genome-name=GRCh38 
then genome-size=GRCh38 .chrom.sizes\ and everyting else I kept the same.
$ snaptools snap-pre  \
	--input-file=demo.bam  \
	--output-snap=demo.snap  \
	--genome-name=GRCh38  \
	--genome-size=GRCh38.chrom.sizes  \
	--min-mapq=30  \
	--min-flen=0  \
	--max-flen=1000  \
	--keep-chrm=TRUE  \
	--keep-single=TRUE  \
	--keep-secondary=False  \
	--overwrite=True  \
	--min-cov=100  \
	--verbose=True

I get an error snaptools snap-pre: error: the following arguments are required: --genome-size,
How do I fix that?
Thank you

**Comment by r3fang** [comment]
do you have this file `GRCh38.chrom.sizes`?

**Comment by EDYAC** [comment]
I actually don't have this file

**Comment by r3fang** [comment]
no worries, you can download GRCh38.chrom.sizes file from here with the following command:

```bash
> wget http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.chrom.sizes
> snaptools snap-pre 
--input-file=demo.bam 
--output-snap=demo.snap 
--genome-name=hg38 
--genome-size=hg38.chrom.sizes 
--min-mapq=30 
--min-flen=0 
--max-flen=1000 
--keep-chrm=TRUE 
--keep-single=TRUE 
--keep-secondary=False 
--overwrite=True 
--min-cov=100 
--verbose=True
```
Can you try this again and let me know if it works?

**Comment by r3fang** [comment]
Also, you need to change `demo.bam` to you own bam file as well. Besides that, the bam file has to be modified before running this command

**Comment by EDYAC** [comment]
I did what you asked, I also change the demo.bam to the name of my bam file, now I get an error mybam.bam is not a sorted by read name!

**Comment by EDYAC** [comment]
I guess this is what you mean by "has to be modified before running this command"?

**Comment by r3fang** [comment]
yes. this is the step-by-step instruction about how to run snaptools with cell-ranger bam file

https://github.com/r3fang/SnapATAC/wiki/FAQs#cellranger_output

**Comment by EDYAC** [comment]
I need to install samtools I guess first

**Comment by r3fang** [comment]
or you can use the bed file which is also in the instruction

**Comment by EDYAC** [comment]
the bed file I have is raw_peak_bc_matrix_mes_peaks.bed is that the usual bed file?

**Comment by r3fang** [comment]
no, that's the peaks coorindates. do you have a tsv.gz file?

**Comment by EDYAC** [comment]
yeah its called donor_fragments.tsv.gz is that what you are asking for?

**Comment by r3fang** [comment]
yes, you can also use donor_fragments.tsv.gz as input for snaptools by following the instruction:
https://github.com/r3fang/SnapATAC/wiki/FAQs#cellranger_output

**Comment by EDYAC** [comment]
OK I will try this one and let you know.
Thank you

**Comment by r3fang** [comment]
no problem! Anytime.

**Comment by EDYAC** [comment]
Hi,
I followed the instruction to start with the fragments.tsv file, 
I did the $ sort -k14,4...
then I did the $ gzip
and when I tried to do the $ snaptools snap-pre  \

I get an error message donor_fragments.bed.gz is not a sorted by read name
I don't know know what Im doing wrong, following the instruction I got the bed file then I compressed it

**Comment by r3fang** [comment]
hi, i think it should be `sort -k4,4...` not `sort -k14,4...`

**Comment by EDYAC** [comment]
oh ok, it's written -k14,4 
what k4,4 represent?

**Comment by r3fang** [comment]
Sorry for the error. It means sort the file based on the fourth column which is the barcode column

**Comment by EDYAC** [comment]
Ok, I made the adjustment and its running now, I will let you know what happens, no worries, thank you so much for your help and hope the error get fixed. I really like this tool so far

**Comment by EDYAC** [comment]
Hi,
I have a question, might be stupid, am I suppose to be running this on my personal laptop or I should be connected to the cluster, I started yesterday night and still it's not done, the fragments.tsv file is 6Gb. Thank you

**Comment by r3fang** [comment]
It’s a bit surprise that sorting takes this long. It’s better to have a sever or cluster because the downstream analysis also requires certain memory

**Comment by EDYAC** [comment]
In the tutorial, its written $ sort -k4,4... should it be $ samtools sort -k4,4..?

**Comment by r3fang** [comment]
No samtools sort is different function

**Comment by EDYAC** [comment]
Ok it actually worked, I got two files, .snap and .snap.qc
As you know Im using Human genome, I changed mm10 to hg38, I kept everything else the same as in the tutorial, like --min-mapq=30, is that ok for human? 
I couldn't find documentation for what those things mean.

**Comment by r3fang** [comment]
Ok it actually worked, I got two files, .snap and .snap.qc
As you know Im using Human genome, I changed mm10 to hg38, I kept everything else the same as in the tutorial, like --min-mapq=30, is that ok for human?

**_Yes but you need to change mm10.chrom.size to hg38.chrom.size_**

I couldn't find documentation for what those things mean.

```
snaptools snap-pre -h 
```

**Comment by werhmk** [comment]
Hello,
Can this tool be used for plant scATAC? 
Because, I try to prepare the snap file using the snaptools snap-pre function, I found the --genome-name seems only include the human genome? 
'''
snaptools snap-pre
--genome-name GENOME_NAME
                        genome identifier (i.e. hg19, mm10)
'''

Couldn't we prepare a genome fasta or gff/gtf file ourselves instead of this?
