### ISSUE TITLE
snap-add-bmat

### ISSUE THREAD

**Issue by EDYAC** [r3fang/SnapATAC#27]
Hello,
I generated the .snap file,
following the tutorial, the next step is the snap-add-bmat,
I input this code:
$ snaptools snap-add-bmat	\
--snap-file=scATAC_BMMC_CLL_donor.snap \
--bin-size-lis 5000	\
--verbose=True

Get an error: error: argument : invalid choice: 'snap-add-bmat--snap-file=atac_v1_adult_brain_fresh_5k.snap' (choose from 'dex-fastq', 'index-genome', 'align-paired-end', 'align-single-end', 'snap-pre', 'snap-add-bmat', 'snap-add-pmat', 'snap-add-gmat', 'dump-fragment', 'dump-barcode', 'call-peak', 'louvain', 'snap-del')

Any help on how to deal with that?

**Comment by EDYAC** [comment]
$ snaptools snap-add-bmat	\
--snap-file=scATAC_BMMC_CLL_donor.snap \
--bin-size-lis 5000	\
--verbose=True

I actually included the \ in my code so this is not the issue

**Comment by r3fang** [comment]
how about this

```bash
snaptools snap-add-bmat --snap-file=scATAC_BMMC_CLL_donor.snap --bin-size-lis 5000 --verbose=True
```

**Comment by EDYAC** [comment]
Yep, this solved my problem,
Thank you
