### ISSUE TITLE
Human vs. Mice Step 3. Fragments-in-promoter ratio 

### ISSUE THREAD

**Issue by EDYAC** [r3fang/SnapATAC#28]
Hello,
If Im using Human genome, will the promotor file provided in step 3 work or I need a human promoter.bed file? 
Also Is this a necessary step? can I move to step 4 without going through step 3?
Thank you

**Comment by r3fang** [comment]
If it’s 10X data I recommend to run this step but if you just want to run through the pipleline, you can skip this step and get the cluster

**Comment by EDYAC** [comment]
it's actually 10X, so it's the same thing regardless of being human or mice genome?

**Comment by r3fang** [comment]
No the list for human and mouse is different

**Comment by EDYAC** [comment]
Any suggestions? where to get it from?

**Comment by r3fang** [comment]
You can download from UCSC genome browser. They have an option to download promoter 2kb upstream of tss.

**Comment by EDYAC** [comment]
Hi,
I'm having a hard time finding the promoter list you are talking about,
Would you be able to help please?

**Comment by r3fang** [comment]
use this one:

http://renlab.sdsc.edu/r3fang/share/Fang_2019/published_scATAC/atac_v1_pbmc_10k_fastqs/hg19_promoter.bed
