### ISSUE TITLE
runCluster error

### ISSUE THREAD

**Issue by sam-morris** [r3fang/SnapATAC#3]
Hi, when I try to find clusters using 'runCluster', I get the following error:
File "/Users/smorris/snaptools/bin/snaptools", line 36, in <module>
    from snaptools.parser import parse_args
ImportError: No module named snaptools.parser
Error in runCluster.default(x.sp, pca_dims = 1:10, k = 30, resolution = 1,  : 
  'runCluster' call failed

**Comment by r3fang** [comment]
Hi thank you for trying out our method and sorry for not documenting this clearly. We are still testing the method internally. In order to run this step, you will need to install ‘snaptools’ 1.2.5 by ‘pip install —install snaptools==1.2.5’ which requires python2.7. After installing snaptools, when running runCluster, set the tag ‘path_to_snaptools’ to the excutable snaptools file. Please let me know if it still does not work.

**Comment by r3fang** [comment]
Can you make sure 

/Users/smorris/snaptools/bin/snaptools

Is an excutable? This error may be raised because the python version is not 2.7 or because snaptools version is not 1.2.5. If it’s snaptools installation failed. Please feel free to let me know if snaptools installation failed

**Comment by sam-morris** [comment]
Thanks very much for making the method available! Yes, it is an executable. I downgraded to python version 2.7 and snaptools seems to be working - it doesn't look like it failed

**Comment by r3fang** [comment]
Thanks! if it is still not working. Do you mind running the following command 
```bash
$ /Users/smorris/snaptools/bin/snaptools
```

does it output the following message?

```
usage: snaptools [-h]  ...

Program: snaptools (A module for working with snap files in Python)
Version: 1.2.5
Contact: Rongxin Fang
E-mail:  r4fang@gmail.com

optional arguments:
  -h, --help        show this help message and exit

functions:

    dex-fastq       Decomplex fastq file.
    index-genome    Index reference genome.
    align-paired-end
                    Align paired-end reads.
    align-single-end
                    Align single-end reads.
    snap-pre        Create a snap file from bam or bed file.
    snap-add-bmat   Add cell x bin count matrix to snap file.
    snap-add-pmat   Add cell x peak count matrix to snap file.
    snap-add-gmat   Add cell x gene count matrix to snap file.
    dump-fragment   Dump fragments of selected barcodes from a snap file.
    dump-barcode    Dump barcodes from a snap file.
    call-peak       Call peak using selected barcodes.
    louvain         Louvain communities finding.

```

**Comment by sam-morris** [comment]
Yes, it does output that message

**Comment by r3fang** [comment]
Sorry for the bug. this never happened before. my suspicion is that you probably have python of different version installed, the environment where you are running SnapATAC, python3 is still the default version (for example, maybe you have opened a new screen). This is only my guess. Anyway, I am working on removing runCluster's dependency on snaptools now,  will keep you posted once it is done (later today). Meanwhile, you can still proceed to the rest of the analysis which does not require clustering result. Thanks!

**Comment by r3fang** [comment]
hey, I have updated SnapATAC, please reinstall it by `install_github(r3fang/SnapATAC)`. After installation, for `runCluster`, by default it now uses igraph cluster_louvain for indentifying clusters but this does not support resolution. Alternatively you can still set `path_to_snaptools` to `snaptools` which allows for different resolutions. This can serve as a temporary solution.

**Comment by sam-morris** [comment]
Works great now - thanks very much for your help!

**Comment by r3fang** [comment]
FYI, we have updated the pipeline to a new version which 1) solves the problem for runClsuter; 2) reduces the memory usage; 3) offers better visualization options; 4) allows for combining multiple samples.

**Comment by sam-morris** [comment]
I'll try it out - thanks very much!
