### ISSUE TITLE
Merging 3+ samples

### ISSUE THREAD

**Issue by JBreunig** [r3fang/SnapATAC#30]
Thanks for the intuitive package and frequent updates with more functionality!

What is the procedure for combining 3 samples or more as you mention below?

> Hi,
> 
> Thank you for your kind message and thanks for try it! This is great question. 
> 
> The answer is yes. SnapTools does not support merge of multiple "snap" files but "SnapATAC" supports to merge multiple snap object in R. Here is one example how SnapATAC analyzes two samples together [here](https://github.com/r3fang/SnapATAC/blob/master/examples/10X_15k/10X_15k.md). You can merge multiple snap objects once they share cell-by-bin matrix of the same bin size. Last time i tried, I have no problem of merging up to 70 samples.
> 
> The reason that snaptools does not merge multiple snap files in to a single one is because I am trying to avoid creating a giant matrix that slows down the read-in function in SnapATAC. Also, as you mentioned, it would be nice to keep each sample separate so this can be ran in parallel.
> 
> Does it answer your question?
> 
> Best
> -Rongxin
> 
> _Originally posted by @r3fang in https://github.com/r3fang/SnapATAC/issues/13#issuecomment-487117556_

**Comment by r3fang** [comment]
Just by changing the file.list and sample.list to include 3 or more samples when creating the snap object

**Comment by JBreunig** [comment]
Sorry, it was a glitch with a snap file that prevented the 3rd file from loading when I had first tried it ;)
