### ISSUE TITLE
error in createSnap()

### ISSUE THREAD

**Issue by IMJoeyZhu** [r3fang/SnapATAC#31]
When I running the `createSnap()` I got these following error information:
```R
> x.sp = createSnap(file="atac_v1_adult_brain_fresh_5k_2.snap",sample="atac_v1_adult_brain_fresh_5k",num.cores=1)
Epoch: reading the barcode session ...
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
Error in data.frame(barcode, TN, UM, PP, UQ, CM) : 
  arguments imply differing number of rows: 0, 8033
```
I check my R version: 3.5.1 and upgrade the rhdf5 package to version: 2.26.2. 
But still get these information, how can I fix it?

Best,

**Comment by r3fang** [comment]
This is likely because the dependencies Rhdf5 and Rhdf5lib are not successfully installed. Can you install these two R packages separately? 

https://bioconductor.org/packages/3.7/bioc/html/rhdf5.html

Let me know if this still does not solve the problem

**Comment by IMJoeyZhu** [comment]
I tried re-install these two R packages separately, but that not helpful, I still got the same error as before. T_T~~~

**Comment by IMJoeyZhu** [comment]
I run this on linux, and you advices are pretty helpful.
I upgraded these two R packages and found out it works.
Thanks a lot!

Best
