### ISSUE TITLE
chromVAR integration

### ISSUE THREAD

**Issue by JBreunig** [r3fang/SnapATAC#34]
Apologies for the many questions, I just want to confirm that I'm understanding the nuances of SnapATAC.  

For the motif variability matrix, do we take that output and plot it as shown here:
https://greenleaflab.github.io/chromVAR/articles/Articles/Applications.html

Thanks in advance!

**Comment by r3fang** [comment]
you are right about it. Let me know if you have any question. Sorry for the delay i was traveling.

**Comment by JBreunig** [comment]
Thank you!
