### ISSUE TITLE
error in clustering by `leiden`

### ISSUE THREAD

**Issue by ChickenWangSY** [r3fang/SnapATAC#35]
hi rongxing,
    when i clustered cells by `leiden`, i got the error of packages import:
```
> library(leiden)
> x.sp = runCluster(
+ obj=x.sp,
+ tmp.folder=tempdir(),
+ louvain.lib="leiden",
+ seed.use=10,
+ resolution=1
+ );
Epoch: checking input parameters
Epoch: finding clusters using leiden
Error in py_module_import(module, convert = convert) :
  ImportError: No module named leidenalg
```
then i install `leidenalg` successfully,
```
/zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/bin/pip3.7 install leidenalg numpy igraph
Collecting leidenalg
  Using cached https://files.pythonhosted.org/packages/b6/cc/d76baf78a3924ba6093a3ce8d14e2289f1d718bd3bcbb8252bb131d12daa/leidenalg-0.7.0.tar.gz
Requirement already satisfied: numpy in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (1.15.4)
Collecting igraph
  Downloading https://files.pythonhosted.org/packages/91/15/7c606c483a401dfdcdd19f2688c83585ee3b5ef401bd4e0e647660ef5b3f/igraph-0.1.11-py2.py3-none-any.whl (119kB)
     |████████████████████████████████| 122kB 1.9MB/s
Collecting python-igraph>=0.7.1.0 (from leidenalg)
  Downloading https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz (377kB)
     |████████████████████████████████| 378kB 2.2MB/s
Requirement already satisfied: ipython in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from igraph) (7.2.0)
Requirement already satisfied: traitlets>=4.2 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (4.3.2)
Requirement already satisfied: setuptools>=18.5 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (40.6.3)
Requirement already satisfied: jedi>=0.10 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (0.13.2)
Requirement already satisfied: pickleshare in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (2.0.7)
Requirement already satisfied: pexpect; sys_platform != "win32" in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (4.6.0)
Requirement already satisfied: backcall in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (0.1.0)
Requirement already satisfied: pygments in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (2.3.1)
Requirement already satisfied: decorator in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from ipython->igraph) (4.3.0)
Requirement already satisfied: six in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from traitlets>=4.2->ipython->igraph) (1.12.0)
Requirement already satisfied: ipython-genutils in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from traitlets>=4.2->ipython->igraph) (0.2.0)
Requirement already satisfied: parso>=0.3.0 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython->igraph) (0.3.1)
Requirement already satisfied: wcwidth in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->igraph) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in /zfssz2/ST_MCHRI/COHORT/wangshiyou/software/anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython->igraph) (0.6.0)
Building wheels for collected packages: leidenalg, python-igraph
  Building wheel for leidenalg (setup.py) ... done
  Stored in directory: /home/wangshiyou/.cache/pip/wheels/29/55/48/5a04693a10f50297bcda23819ca23ab3470a61dd911851c8bd
  Building wheel for python-igraph (setup.py) ... done
  Stored in directory: /home/wangshiyou/.cache/pip/wheels/41/d6/02/34eebae97e25f5b87d60f4c0687e00523e3f244fa41bc3f4a7
Successfully built leidenalg python-igraph
Installing collected packages: python-igraph, leidenalg, igraph
Successfully installed igraph-0.1.11 leidenalg-0.7.0 python-igraph-0.7.1.post6
```
and installed `leiden` again. I also tried to install the developmental version but it didn't work.
had you ever met this problem?

regards!

**Comment by r3fang** [comment]
hi there,

you need to install `leiden` R pakcage and python package as well
in R (do not install the develpment version on github):
```
> install.packages("leiden")
```

for python

```
$ install leidenalg numpy python-igraph
```

let me know if it solves the problem

**Comment by ChickenWangSY** [comment]
> hi there,
> 
> you need to install `leiden` R pakcage and python package as well
> in R (do not install the develpment version on github):
> 
> ```
> > install.packages("leiden")
> ```
> 
> for python
> 
> ```
> $ install leidenalg numpy python-igraph
> ```
> 
> let me know if it solves the problem

I did as you advised but it didn't worked. 
I'm `anaconda3` and `python3.7` , `R 3.5,1`.
and i thought i had installed these modules but when i `help(module)` , i got:
```
>>> help("leidenalg")
problem in leidenalg - DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

>>> help("igraph")
problem in igraph - DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

```

**Comment by r3fang** [comment]
Hi,

You can follow deailed instruction about how to install leiden
https://github.com/vtraag/leidenalg

**Comment by xinhuang420** [comment]
> leidenalg

@ChickenWangSY 
Hi, I have the same problem.

I installed package by ' system("pip install leidenalg python-igraph") ' in python2.7 as recommended.

'library(leiden)'  is successful.

Please let me know the solution of the problem. Thank you very much!

**Comment by r3fang** [comment]
Did you install both python package and `leiden` R pakcage?

**Comment by xinhuang420** [comment]
@r3fang 
Thanks for reply. Your pipeline is really useful and important.

Yes, I installed both python package and leiden R pakcage.（Please see the screenshot）
<img width="696" alt="WechatIMG248" src="https://user-images.githubusercontent.com/48995047/58441666-c2f65100-80b1-11e9-9f02-8f5b110b4b18.png">

And I used conda to  create the environment of python2.7

Thank you very much!

Best wishes!
Xin

**Comment by r3fang** [comment]
1) This is copied from https://cran.r-project.org/web/packages/leiden/vignettes/run_leiden.html Leiden only supports python 2

```
This package requires the 'leidenalg' and 'igraph' modules for python (2) to be installed on your system.
```

2) you can also use `louvain.lib=R-igraph` which identifies cluster using `louvain` algorithm but does not support `resolution`. 

Let me know if this solves your problem

**Comment by xinhuang420** [comment]
@r3fang 
Thanks for your tutorial, which is really useful.
I can solve my problem after following your suggestion.
I used louvain.lib=R-igraph

Your pipeline performance well and I can get good result.
<img width="819" alt="WechatIMG249" src="https://user-images.githubusercontent.com/48995047/58444852-03f96000-80c8-11e9-814b-aaeebf071620.png">

Once again thank you for your time and have a great day! 

Xin

**Comment by r3fang** [comment]
You are very welcome! I will close this issue, please feel free to let me know if you have any other question!

**Comment by ChickenWangSY** [comment]
> > leidenalg
> 
> @ChickenWangSY
> Hi, I have the same problem.
> 
> I installed package by ' system("pip install leidenalg python-igraph") ' in python2.7 as recommended.
> 
> 'library(leiden)' is successful.
> 
> Please let me know the solution of the problem. Thank you very much!

thanks for your advice. i just solved it by running it at the windows.  `leiden` in windows are running successfully.

**Comment by JayoungRyu** [comment]
Hi, I have the same problem and Leidenalg says it doesn't support python version lower than 3.5. 
Plus, I wasn't able to install leidenalg in python 2.7 environment. 
Would there be method to use leiden algorithm or to use lower resolution cluster annotation?
