### ISSUE TITLE
Add doSNOW to Imports or Suggests?

### ISSUE THREAD

**Issue by hypercompetent** [r3fang/SnapATAC#36]
Hi Rongxin,

I ran into this error during installation on a Windows machine (below). After running install.packages("doSNOW"), it worked fine. 

It looks like this might only be required for `runLDA()`, so maybe it should go in Suggests in DESCRIPTION.

Thanks!
-Lucas

* installing *source* package 'SnapATAC' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'doSNOW'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'SnapATAC'
* removing 'C:/Users/lucasg/Documents/R/win-library/3.6/SnapATAC'

**Comment by r3fang** [comment]
Hi Lucas,

Thanks for the suggestion. Indeed, I just added runLDA recently, will update the package today.

Best
-Rongxin
