### ISSUE TITLE
snap file for non-standard genome

### ISSUE THREAD

**Issue by vagarwal87** [r3fang/SnapATAC#38]
Hello,

I'm using a plant genome and ran into the issue that the genome_name must match one pre-defined in the accepted list.

I ran this command:

`snaptools snap-pre --input-file=mapped.bam --output-snap=mapped.snap --genome-name=plant --genome-size=plant.gs --min-mapq=30 --min-flen=0 --max-flen=1000 --keep-chrm=TRUE --keep-single=FALSE --keep-secondary=FALSE --overwrite=True --min-cov=100 --verbose=True
`

and got this error: "error: --genome-name unrecoginized genome identifier plant".

All of the steps before this worked perfectly including index creation and read mapping. Is there any specific reason the package can't be used on any arbitrary genome, and is there a quick fix that can relax the constraint of the genome matching one in the GENOMELIST?

Thanks for your help!
Vikram

**Comment by r3fang** [comment]
Hi Vikram,

Thanks for trying it out! Yes, simple solution - just change it to `mm10`. SnapTools currently only allows for existing genome reference name such as hg19 or mm10. If you have a customized genome such as mouse human concatenated genome, it is fine to use the name `hg19` or  `mm10`. This parameter is currently not used in the downstream analysis. 

Let me know if this does or does not work
Best,

**Comment by vagarwal87** [comment]
Hello, Thanks for the fix. This step seemed to execute successfully now!

Best,
Vikram

**Comment by r3fang** [comment]
Great! I'll close this issue but plz let me know if you have other question

**Comment by billzt** [comment]
Well, I recommend to write this into the FAQ otherwise it would be extremely confused.
