### ISSUE TITLE
How to extract matrices made by "snap-pre"?

### ISSUE THREAD

**Issue by seishin0125** [r3fang/SnapATAC#4]
Hi, I'm thinking of applying cell-by-bin matrices to another scATAC-analysis pipelines such as pseudo-trajectory analysis.

In order to do so, I tried to extract cellxbin matrix (bmat) from mos object imported by data(mos).
I have confirmed that mos contains "bmat" attribute by attributes() function, however, I couldn't get bmat by mos$bmat.
Error in mos$bmat : $ operator not defined for this S4 class

Could you teach me how to extract bmat from "snap" object?

**Comment by r3fang** [comment]
Hi, you can extract bmat by slot(mos,bmat)

**Comment by seishin0125** [comment]
Thanks so much!

**Comment by seishin0125** [comment]
Thank you very much for quick reply.
In my case, slot() function did not go well. Instead, I could extract bmat by "mos@bmat".

Again, thank you so much for your help. I'm really looking forward to utilizing this SnapATAC tools for analysing my scATAC data.

**Comment by r3fang** [comment]
Hi! Thank you for using SnapATAC. Please let me know if you have other questions. Also, this version is still under development, I am about to release the first official version which is supposed to run faster and result in better performance, if star this repository,  you will be notified once it is released. -R
