### ISSUE TITLE
10X dataset after snaptools dex-fastq

### ISSUE THREAD

**Issue by znavidi** [r3fang/SnapATAC#41]
Hi,
In the "How to create snap file from 10X dataset" section, it is mentioned that we should run snaptools dex-fastq module to integrate the 10X barcode into the read name, and the output names are:
Library1_1_L001_R1_001.dex.fastq.gz
Library1_1_L001_R3_001.dex.fastq.gz
Library1_2_L001_R1_001.dex.fastq.gz
Library1_2_L001_R3_001.dex.fastq.gz

but you also mentioned that run the rest of the pipeline using Library1_L001_R1_001.fastq.dex.gz and Library1_L001_R3_001.fastq.dex.gz. 
The extension of the output of previous step and the files that you mentioned we should use for the rest of the pipeline is different (.dex.fastq.gz and .fastq.dex.gz). Is it a mistake in the names? Otherwise what do you mean and where are these files?

Thanks

**Comment by r3fang** [comment]
It’s a mistake

**Comment by r3fang** [comment]
Will correct it, thanks for reporting it

**Comment by znavidi** [comment]
Thank you :)
Also, after running dex-fastq command and integrating the barcode into the read name, it is mentioned to combine these two libraries (I think it means any number of different libraries):

$ cat Library1_1_L001_R1_001.fastq.gz Library1_2_L001_R1_001.fastq.gz > Library1_L001_R1_001.fastq.gz
$ cat Library1_1_L001_R3_001.fastq.gz Library1_2_L001_R3_001.fastq.gz > Library1_L001_R3_001.fastq.gz

but the files that I have are from the different lanes (not library, because the only difference they have is in their L001, L002, L003 parts). So I should not combine them, right?
I mean should I run the rest of the pipeline on each of the lane files separately?

**Comment by r3fang** [comment]
Hi there,

If it is the same library (same sample/experiment) just sequenced by different lanes, you should merge them. If it is different libraries, you should not merge them. 

The demo example is different lanes from the same lib.

**Comment by znavidi** [comment]
Thanks

**Comment by znavidi** [comment]
Another question:
By that sentence you mean we should merge Library-L001.dex.fastq.gz and Library-L002.dex.fastq.gz and ... together and align these Library-R1.dex.fastq.gz and Library-R2.dex.fastq.gz files to the reference genome?

**Comment by r3fang** [comment]
Yes

**Comment by r3fang** [comment]
i'll close this issue but feel free to ask any other question
