### ISSUE TITLE
Warning during barcode selection

### ISSUE THREAD

**Issue by JBreunig** [r3fang/SnapATAC#44]
I've previously been using your P50 10X brain tutorial without issue but tried the new code for FRIP/UMI selection and get the warning:

> x.sp = x.sp[which(x.sp@barcode %in% barcodes.sel$barcode)];
> Warning message:
> In max(i) : no non-missing arguments to max; returning -Inf

This leads to x.sp having 0 barcodes. (prior to that line it has 8033).

The barcodes data.frame  has 499703 obs. of 18 variables

Prior to that line, the plots look identical and there are 4098 objects in barcodes.sel

Do you have any suggestions?  

Keep up the great work with all of the additions!

**Comment by r3fang** [comment]
`x.sp@barcode` probably have different barcodes with `barcodes.sel$barcode`. The reason for that is because you generated the snap file from fastq file which does not have "-1" in the barcode. 

```R
x.sp@barcode = paste(x.sp@barcode, "-1", sep="");
```

should solve the problem

**Comment by JBreunig** [comment]
That fixed it, thanks!

**Comment by r3fang** [comment]
Actually, better use this one, dont change the barcode in snap object `x.sp`

```
barcodes.sel$barcode = do.call(c, sapply(barcodes.sel$barcode, function(s) strsplit(s, "-1")))
```

**Comment by JBreunig** [comment]
is this ok:  
barcodes.sel$barcode = do.call(c, sapply(barcodes.sel$barcode, function(s) strsplit(as.character(s), "-1")))

because I got the warning 

> Error in strsplit(s, "-1") : non-character argument

initially

>

**Comment by JBreunig** [comment]
tutorial completes ok like this, thanks again!

**Comment by r3fang** [comment]
no problem. anytime!
--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego
