### ISSUE TITLE
Step 13 - human genes - marker genes

### ISSUE THREAD

**Issue by znavidi** [r3fang/SnapATAC#46]
Hi 

I am running the 13 th step of snapATAC and I downloaded the human hg19 gene list from here:
http://genome.ucsc.edu/cgi-bin/hgTables?command=start

But when I run the codes, my genes list format and gene names are different from those you have declared in marker.genes. Where should I download the compatible version of human genes bed file with marker genes?

And also I would like to know that is the marker.genes list the same in every human and every dataset? or we should change it based on out dataset. And what should we select?

Thanks
Best

**Comment by r3fang** [comment]
> On Jun 5, 2019, at 9:04 AM, znavidi <notifications@github.com> wrote:
> 
> Hi
> 
> I am running the 13 th step of snapATAC and I downloaded the human hg19 gene list from here:
> http://genome.ucsc.edu/cgi-bin/hgTables?command=start <http://genome.ucsc.edu/cgi-bin/hgTables?command=start>
> But when I run the codes, my genes list format and gene names are different from those you have declared in marker.genes. Where should I download the compatible version of human genes bed file with marker genes?
> 
You should define marker genes based on your own gene annotation. Different annotations may have different names.
> And also I would like to know that is the marker.genes list the same in every human and every dataset? or we should change it based on out dataset. And what should we select?
> 
It is different from different samples/dataset. This is sample specific, ones in the example are known for brain data

**Comment by znavidi** [comment]
Thank you :)
