### ISSUE TITLE
Is it possible to label filterCells on a per sample basis?

### ISSUE THREAD

**Issue by AlexChitsazan** [r3fang/SnapATAC#52]
I have three samples, when I look at the AllMerged sample that has all three my intuition would be to make a cutoff at UMIs but when I look on an individual basis, my thought is that filtering the AllMergedIntoOneSnapObject would almost certainly get rid of most reads from sample1. Sample1 plotted individually would make me think the cutoff should be different? Below are my plotbarcodes output of each:
AllMergedIntoOneSnapObject:
![AllMerged](https://user-images.githubusercontent.com/49252382/60220772-0ddbc380-982c-11e9-94ae-0a03d4aabb91.png)
Sample1:
![sample1](https://user-images.githubusercontent.com/49252382/60220769-0d432d00-982c-11e9-858d-80709cdd1951.png)
Sample2:
![sample2](https://user-images.githubusercontent.com/49252382/60220770-0d432d00-982c-11e9-9e13-a9a251b8dc8a.png)
Sample3:
![sample3](https://user-images.githubusercontent.com/49252382/60220771-0d432d00-982c-11e9-98e9-a27014e45f61.png)

**Comment by AlexChitsazan** [comment]
Apologies, I'm realizing that is what you guys do with sciATAC/10x integration example. Is that what you would recommend in this instance? Similar to that?

**Comment by r3fang** [comment]
Absolutely! I recommend to identify barcodes based on log10(UMI) and promoter ratio plot like this one below



--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by r3fang** [comment]
For each sample separately then merge them together 
--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by AlexChitsazan** [comment]
Great thanks for the prompt reply! I notice in the first comment you say like "this one below" but I don't see anything. Did you mean to attach anything?

Also, I'm very familiar with ATAC-seq but new to scATAC, is there a UMI cutoff that would be deemed to low? They all show the bimodal distrubution you discussed but for sample1 above it seems like the cutoff would be 1.25. This would be 17 UMIs, which seems like not nearly enough to detect a good signal qualitatively. I was curious if you had thoughts.

**Comment by r3fang** [comment]
here is the attachment
![image](https://user-images.githubusercontent.com/6808347/60224689-66b15900-9838-11e9-8168-b4ab083b17c0.png)

I usually use 1000 unique fragments as a hard cutoff. I did some simulation, for very different cell lines, single cell ATAC-seq with coverage less than 1,000 will make it hard to distinguish different cell types. Complex tissue where the differences between cell types are subtle probably requires higher coverage.

**Comment by AlexChitsazan** [comment]
Gotcha thanks by unique fragments you mean UMI's correct, not total fragments?

 From my sample1 picture above, the descrepency between log(UMI) and log(total fragment) is on very different scales (UMI = 0~3 while totalfragment=2-5). As I'm typing this I'm realizing that this is probably because there was a ton of duplication and that does actually show in the duplication rate plot. would this be a big red flag for you of a bad sample?

**Comment by r3fang** [comment]
1) Unlike scRNA-seq, scATAC-seq do not have UMI, what I mean is unique fragment. 
2) It depends on many factors, if your library is very complex and deeply sequenced, it is fine to see a high duplicate rate. Also, it's quite common that a library has 60-80% duplicate rates. What really matters is the number of unique fragments after filteration.

**Comment by AlexChitsazan** [comment]
Gotcha. Thanks so much. I really appreciate this. SnapATAC is great. Huge fan.

**Comment by r3fang** [comment]
thank you! appreciate the comments

**Comment by AlexChitsazan** [comment]
How do you make the log10(passed_filters) vs Promoter ratio plots you showed above? I assumed it would be plotting log(UMI) vs promoter ratio but I can't seem to figure it out. 



```
ov = findOverlaps(x.sp@feature, promoter.gr);
idy = queryHits(ov);
promoter_ratio = SnapATAC::rowSums(x.sp[,idy, mat="bmat"], mat="bmat") / SnapATAC::rowSums(x.sp, mat="bmat");
plot(log(x.sp@metaData$UQ + 1,10), promoter_ratio, cex=0.5, col="grey", xlab="log(UMI)", ylab="FIP Ratio", ylim=c(0,1 ));
```

but my graph wasn't at all like yours

**Comment by r3fang** [comment]
what does yours look like?

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by AlexChitsazan** [comment]
Apologies, thought I attached it
[Plot.pdf](https://github.com/r3fang/SnapATAC/files/3336951/Plot.pdf)

**Comment by AlexChitsazan** [comment]
Never mind. I reassigned a variable and it was a bug in my code. Apologies
