### ISSUE TITLE
How to get the bmat or pmat loadings for PC1-50?

### ISSUE THREAD

**Issue by linwang6** [r3fang/SnapATAC#53]
Hi,

I know how to get the PC loadings for each cell (x.sp@smat@dmat) in snapATAC, but how to get the bmat or pmat loadings for each PC? Is there a way to get them? 

Thanks.

**Comment by r3fang** [comment]
Hi,

There is no bmat or pmat top loadings in the method. It performs SVD agains jaccard index. But you can perform differential analysis to identify differential elements

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by linwang6** [comment]
Thanks.
