### ISSUE TITLE
runCluster silencer error. 

### ISSUE THREAD

**Issue by shawnzhangyx** [r3fang/SnapATAC#6]
Hi Rongxin, 

I tried to runCluster with the path to the snaptools, however, it failed to cluster without reporting any error. On the other hand, the R internal igraph cluster method worked (without giving it the path to snaptools). Could you help me figure out why? 
I can send you the link to RData file over Slack if you need it.

**Comment by r3fang** [comment]
can you use igraph for now? I am working on a new version, this function is out of date now

**Comment by shawnzhangyx** [comment]
Sure. Thanks for the comment!
