### ISSUE TITLE
Object x.lsa.lda.sp

### ISSUE THREAD

**Issue by IMJoeyZhu** [r3fang/SnapATAC#65]
![image](https://user-images.githubusercontent.com/37504708/62434564-4d6ec700-b76b-11e9-9174-63191cba9926.png)

There is an object named x.lsa.lda.sp, but I can only find it in the **Step 14. Consensus Clustering** `x.jda.sp@graph@mat = x.jda.sp@graph@mat + x.lsa.logTF.sp@graph@mat + x.lsa.lda.sp@graph@mat`. 
So, is something wrong here?

**Comment by r3fang** [comment]
It should be x.lda.sp

**Comment by IMJoeyZhu** [comment]
OK, got it. Thanks! It is really helpful.
