### ISSUE TITLE
Downloading SnapATAC 

### ISSUE THREAD

**Issue by smoot-samuel** [r3fang/SnapATAC#67]
Hello, I am having a little trouble installing SnapATAC. When I run the github_install command I get the following errors:

> install_github("r3fang/SnapATAC")
Downloading GitHub repo r3fang/SnapATAC@master
   checking for file ‘/private/var/folders/ws/qbfvzq1x1n74904k5z6b8sgh0000gn/T/R✔  checking for file ‘/private/var/folders/ws/qbfvzq1x1n74904k5z6b8sgh0000gn/T/RtmpQy6uNo/remotes26a02fc21659/r3fang-SnapATAC-595a257/DESCRIPTION’
─  preparing ‘SnapATAC’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SnapATAC_1.0.0.tar.gz’
   
* installing *source* package ‘SnapATAC’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘doSNOW’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘SnapATAC’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SnapATAC’
**Error: Failed to install 'SnapATAC' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ws/qbfvzq1x1n74904k5z6b8sgh0000gn/T//RtmpQy6uNo/file26a03375650f/SnapATAC_1.0.0.tar.gz’ had non-zero exit status**

**Comment by r3fang** [comment]
Can you install package “doSNOW” first and try it again?

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by smoot-samuel** [comment]
Totally missed that. Thanks. Resolved.
