### ISSUE TITLE
create snap file for human and mouse samples

### ISSUE THREAD

**Issue by znavidi** [r3fang/SnapATAC#68]
Hi there, 

Thank you for your interesting tool.
I have a question regarding whether it is possible to create a snap file for fastq or bam files (or a tsp file) that are samples from both human and mouse data?

Best,
Zeinab

**Comment by r3fang** [comment]
Yes, but can you specify your question

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by znavidi** [comment]
Thanks for your prompt answer. 
Actually I would like to create snap file for https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129785 dataset which has 4 mouse sample files out of all 67 sampels (with probably lots of single cells) and there is a fragments.tsv file in the GEO website that I can create bam file from. I got hg38 as reference file input to snaptools in my first try, but this way I am ignoring mouse data, right? 
do you have any better suggestion for analyzing this data ?

Best
Zeinab

**Comment by r3fang** [comment]
Hi there,

1) you can actually create the snap file directly from  fragments.tsv file, once you sort the fragments based on the barcode column.
2) the genome tag in snap tools is so far useless, it will not filter any fragments.

Best,
--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by znavidi** [comment]
Thank You Rongxin :)


Best
