### ISSUE TITLE
differential peaks by cluster

### ISSUE THREAD

**Issue by ellenhong1** [r3fang/SnapATAC#74]
Are there any snapATAC tools that I can use to pull out differential peaks that identify each cluster after running findDAR? I've successfully used runHomer and identified motifs that are enriched inside the DARs, but I would like to identify the peaks that are at the essence of each cluster and use runHOMER on those per cluster. Thank you!

**Comment by r3fang** [comment]
Hi yes,

x.sp@peak[idy,] in which idy is the differential peak index. Let me know if this does not work

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by r3fang** [comment]
If you can run Homer one differential peaks, this should not be wrong. Are you sure idy is the index of differential peaks ?

--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by r3fang** [comment]
Hi,

if you can extract the peaks, can you convert it to a data.frame and write it down to the disk? `as.data.frame(x.sp@peak[idy_C2,])`, i don’t fully understand your question, if you can be more specific, I can provide more advice 

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by ellenhong1** [comment]
Hi, 

Yes- I just realized that anything in x.sp@peak[idy_C2,] is a differential peak that defines that cluster and I have successfully converted it to a data.frame. Thank you so much for your help!

**Comment by r3fang** [comment]
no problem!

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego
