### ISSUE TITLE
Gencode.vM16.gene.bed 404 not found

### ISSUE THREAD

**Issue by ScienceBear** [r3fang/SnapATAC#75]
Hi Rongxin,

I'm at step 13 in the 10X mouse brain tutorial. When I input:
system("wget http://renlab.sdsc.edu/r3fang/share/Fang_2019/MOs_snATAC/genes/gencode.vM16.gene.bed");

I get a 404 Not Found error. Is the url correct?

Best wishes,

Luke

**Comment by r3fang** [comment]
Hi Luke,

Please download the gene annotation from here:
https://www.dropbox.com/sh/pkyloalmvrcw7fg/AAAyMUTFS-569pHJl5DXA2RGa?dl=0 <https://www.dropbox.com/sh/pkyloalmvrcw7fg/AAAyMUTFS-569pHJl5DXA2RGa?dl=0>

Best,
--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego
