### ISSUE TITLE
STEP 9. ERROR  input matrix of obj1 and obj2 do not match

### ISSUE THREAD

**Issue by yasserIRCM** [r3fang/SnapATAC#79]
Hi there.

I need some insight into this function that I don't understand completely (I am trying to be generous with my brain today, because frankly speaking I didn't understand it at all)

Error in runDiffusionMapsExtension(obj1 = x.landmark.sp, obj2 = x.query.sp,  : 
  dimentions of input matrix of obj1 and obj2 do not match
> x.landmark.sp
number of barcodes: **5999**
number of bins: 479013
number of genes: 0
number of peaks: 0
number of motifs: 0
> x.query.sp
number of barcodes: **2894**
number of bins: 479013
number of genes: 0
number of peaks: 0
number of motifs: 0

so afterwards I tested with exactly half my barcodes 4447 and it worked only if we didn't filter out cells of bin coverage less than 1,000 (because if we do, we end up with landmark=4446 and x.query.sp=4447, which stop the pipeline from progressing)

is there any downside to reducing our size from 8894 to this number 4447? does it that our sample size has been halved? also does it reduce the robustness of the statistical testing needed afterwards.

thanks a lot 
regards.

**Comment by r3fang** [comment]
Hi there, 

This is clearly a bug, I will fix it today. I just updated this tutorial two days ago, it is still ongoing process. The sampling-extension is for a large dataset that has over 10,000 cells, in your case, I don’t think you need to perform sampling-extension. Instead, you can treat your x.sp just as the landmarks. 


--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by yasserIRCM** [comment]
Hi there

could you please tell how to use the x.sp directly. because I skipped the sampling step 4 as well as  step 9. but when we can't plot anything. it returns that the dimensional reduction isn't complete.

could you tell me what I missed. 

thanks a lot

**Comment by r3fang** [comment]
can you check the first example in the GitHub which does not require sampling. Also, you need to update the package to the latest version.  

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego
