### ISSUE TITLE
Error in creating bmat

### ISSUE THREAD

**Issue by znavidi** [r3fang/SnapATAC#82]
Hi, 

Thank you for your tool. I am analyzing some of the 10X scATAC-seq data with SnapATAC and while creating bmat from snap files this error happens for some of the samples in this page (https://support.10xgenomics.com/single-cell-atac/datasets):

Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :    Not enough memory to read data! Try to read a subset of data by specifying the index or count parameter. 
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :    Not enough memory to read data! Try to read a subset of data by specifying the index or count parameter.

I have never seen this error before and I don't think it related to the size of barcodes, because there are some samples with much higher number of barcodes that work fine while some other samples with different rang of barcode number get this error.

I would really appreciate if have any suggestion for me to solve this problem.

Best,

**Comment by znavidi** [comment]
Hi, 
Since I have not been able to solve this problem, any help from you would be appreciated.

Best,

**Comment by zhongjixing** [comment]
hi,
Have you solve this problem? I encountered the same error when running addPmatToSnap.

**Comment by zhongjixing** [comment]
I updated rhdf5 to 2.30.0 and the problem is gone.
