### ISSUE TITLE
Bug report in runDiffusionMaps

### ISSUE THREAD

**Issue by abayegan** [r3fang/SnapATAC#83]
Hi,

The `runDiffusionMaps()` functions produces the following error for samples with lower than 1000 cells:

> Error in sample.int(length(x), size, replace, prob) : 

> cannot take a sample larger than the population when 'replace = FALSE'

This is because of the line `idx.ds<- sort(sample(x = seq(row.covs), size = 1000, prob = sampling_prob))`  in the `trainRegression()` function.

**Comment by r3fang** [comment]
if you update the package to the latest version and follow the first or second example, the error should be gone.
