### ISSUE TITLE
could not find function "runDiffusionMaps"

### ISSUE THREAD

**Issue by luzgaral** [r3fang/SnapATAC#85]
I get 'could not find function "runDiffusionMaps" with SnapATAC 1.0.0 

However, runDiffusionMaps is described in the package documentation
?runDiffusionMaps

**Comment by znavidi** [comment]
Hi, 

I have updated the SnapATAC now and still have the same problem, could somebody help me understand what is the problem and how it could be solved?thanks

Best

**Comment by znavidi** [comment]
It seems it did not update correctly and now it works fine. thanks
