### ISSUE TITLE
Installing SnapATAC after recent updates

### ISSUE THREAD

**Issue by RZiffra** [r3fang/SnapATAC#86]
Hi Rongxin,

I was trying to install SnapATAC after your recent updates and ran into the following error:
> install_github("r3fang/SnapATAC")
Downloading GitHub repo r3fang/SnapATAC@master
✔  checking for file ‘/tmp/Rtmp0qcFr2/remotes1596722e864f/r3fang-SnapATAC-b046464/DESCRIPTION’ ...
─  preparing ‘SnapATAC’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SnapATAC_1.0.0.tar.gz’
   
Installing package into ‘/home/rziffra/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘SnapATAC’ ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from '/tmp/RtmpZggkNa/R.INSTALL1d0ab5e4fcc/SnapATAC/R':
  runJDA.R
ERROR: unable to collate and parse R files for package ‘SnapATAC’
* removing ‘/home/rziffra/R/x86_64-pc-linux-gnu-library/3.6/SnapATAC’
* restoring previous ‘/home/rziffra/R/x86_64-pc-linux-gnu-library/3.6/SnapATAC’
Error: Failed to install 'SnapATAC' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp0qcFr2/file1596756853cd/SnapATAC_1.0.0.tar.gz’ had non-zero exit status

It looks like the runJDA.R script is no longer present in the R directory but still expected.

Thanks,
Ryan

**Comment by r3fang** [comment]
hi Ryan,

I am still updating the package, can you install it later today. I will keep you posted. 


--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by ccruizm** [comment]
Looking forward to it! I was also updating the package and have the same issue.

**Comment by r3fang** [comment]
it should be fixed now.
