### ISSUE TITLE
runVIZ for 3D plotting

### ISSUE THREAD

**Issue by yasserIRCM** [r3fang/SnapATAC#87]
Hi

I would like to have three UMAP embeddings per cell to have a 3D plot. so I installed umap-learn
using 
install.packages("reticulate")
library(reticulate)
reticulate::py_install(packages ='umap-learn')

yet runViz is rejecting the command and reporting the following message
Error in runViz1(obj = x.sp, tmp.folder = tempdir(), dims = 3, eigs.dims = c(1:26),  : 
  Please install umap - learn more at https://cran.r-project.org/web/packages/umap/index.html

could you please let me know how to modify the runviz source so I can 3 UMAP embeddings?

thanks a lot.

**Comment by r3fang** [comment]
Hi,
maybe try this:
`umap.cor =umap(x.sp@smat@dmat[,1:26])`

Unfortunately, snapATAC does not support visualizing 3D plot.

Best,

**Comment by yasserIRCM** [comment]
ok, I will try it and let you know

**Comment by yasserIRCM** [comment]
Hi there 
I used this
umap.cor =umap(x.sp@smat@dmat[,1:26], method="umap-learn", n_components=3)

and it worked
thanks a lot I am closing the issue
