### ISSUE TITLE
align-single-end error

### ISSUE THREAD

**Issue by dinhdiep** [r3fang/SnapATAC#9]
Hi Rongxin,

For some odd reasons, align-single-end would not run unless I comment out line #116 in parser.py.

Best,

Dinh

**Comment by r3fang** [comment]
Hi Dinh,

Sorry for the trouble! In fact, the single-end alignment was much less frequently used. the bug you have reported should be fixed now. If you can reinstall snaptools by `pip install snaptools`, the issue should be gone. Let me know if not. 

Best,
Rongxin

**Comment by dinhdiep** [comment]
Yes, it is running without error! Thank you!

**Comment by r3fang** [comment]
Good to know! Feel free to let me know if you have any other question
