### ISSUE TITLE
snap has no AM session

### ISSUE THREAD

**Issue by hjack123** [r3fang/SnapATAC#92]
$ snaptools snap-pre  \
	--input-file=atac_v1_adult_brain_fresh_5k.snap.nsrt.bam  \
	--output-snap=atac_v1_adult_brain_fresh_5k.snap  \
	--genome-name=mm10  \
	--genome-size=mm10.chrom.sizes  \
	--min-mapq=30  \
	--min-flen=50  \
	--max-flen=1000  \
	--keep-chrm=TRUE  \
	--keep-single=FALSE  \
	--keep-secondary=False  \
	--overwrite=True  \
	--max-num=20000  \
	--min-cov=500  \
	--verbose=True

I created snap with 10x outputs bam file. but then 
> showBinSizes(snapfile);
[1] "Warning @check.bin.size: '/AM/binSizeList' not found in  test.snap"
numeric(0)
> x.sp = addBmatToSnap(x.sp, bin.size=5000, num.cores=1);
[1] "error: the following nsap files do not contain AM session"

How do i write the AM session? Thank you!!

**Comment by yeswzc** [comment]
Hi Hjack123,
Could you tell me how did you solve this issue? (if you did) 

Thanks!
ZC

**Comment by r3fang** [comment]
Hi,

You need to run add-bmat after running snap-pre

**Comment by yeswzc** [comment]
> Hi, You need to run add-bmat after running snap-pre
> […](#)
> Sent from my iPhone
> On Sep 28, 2019, at 11:20 PM, Zhichao Wu ***@***.***> wrote: Hi Hjack123, Could you tell me how did you solve this issue? (if you did) Thanks! ZC — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks for your amazing quick reply.

**Comment by brianpenghe** [comment]
> Hi Hjack123,
> Could you tell me how did you solve this issue? (if you did)
> 
> Thanks!
> ZC

snaptools snap-add-bmat \
    --snap-file=possorted_bam.snap \
    --bin-size-list 1000 5000 10000 \
    --verbose=True
